{% set name = "hclust2" %}
{% set version = "1.0.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d2fc4033b27afb1b718834c33c05011f203839545a4da8792db2aaf87f75fe8f" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/SegataLab/hclust2/archive/1.0.0.tar.gz

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib <2.0.0
    - pandas
    - biopython
    - pyqi

test:
  commands:
    - hclust2.py --help

about:
  home: https://bitbucket.org/nsegata/hclust2
  license: MIT
  license_family: MIT
  summary: 'Hclust2: A tool for plotting heatmaps'
  description: A tool for plotting hierarchically clustered heatmaps
  doc_url: https://bitbucket.org/nsegata/hclust2

