{% set name = "hclust2" %}
{% set version = "1.0.0_3d589ab" %}
{% set hash_type = "sha256" %}
{% set hash_value = "bd3ac7e24cf47eb2e1ee46f4165987cfee2c542babcadc705aee8da3bca33438" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: 3d589ab2cb68.tar.gz
  url: https://bitbucket.org/nsegata/hclust2/get/3d589ab2cb68.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib<2.0.0
    - pandas
    - biopython
    - pyqi

test:
  commands:
    - hclust2.py --help

about:
  home: https://bitbucket.org/nsegata/hclust2
  license: MIT
  license_family: MIT
  summary: 'Hclust2: A tool for plotting heatmaps'
  description: A tool for plotting hierarchically clustered heatmaps
  doc_url: https://bitbucket.org/nsegata/hclust2

