{% set name = "anadama2" %}
{% set version = "0.6.7" %}
{% set hash_type = "sha256" %}
{% set hash_value = "9863240bca0262b67d623913ebf14abc277b6977c8462a46fedd6f060fd9108d" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - networkx ==1.11
    - leveldb ==0.193
    - six
    - cloudpickle ==0.2.1
    - pweave ==0.25
    - markdown
    - subprocess32
  run:
    - python
    - networkx ==1.11
    - leveldb ==0.193
    - six
    - cloudpickle ==0.2.1
    - pweave ==0.25
    - markdown
    - subprocess32

test:
  imports:
    - anadama2
    - anadama2.grid
    - anadama2.util

about:
  home: http://huttenhower.sph.harvard.edu/anadama2
  license: MIT
  license_family: MIT
  summary: 'AnADAMA2: Another Automated Data Analysis Management Application 2'
  description: AnADAMA2 is the next generation of AnADAMA. AnADAMA is a tool to create reproducible workflows and execute them efficiently. Tasks can be run locally or in a grid computing environment to increase efficiency. Essential information from all tasks is recorded, using the default logger and command line reporters, to ensure reproducibility. A auto-doc feature allows for workflows to generate documentation automatically to further ensure reproducibility by capturing the latest essential workflow information. AnADAMA2 was architected to be modular allowing users to customize the application by subclassing the base grid meta-schedulers, reporters, and tracked objects (ie files, executables, etc).
  doc_url: http://huttenhower.sph.harvard.edu/anadama2

extra:
  recipe-maintainers: 'biobakery-users@googlegroups.com'
