{% set name = "lefse" %}
{% set version = "1.1.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "26f2f9d3e5ee44e588fab4d58bffcb811d6bdab39b6c7d0ae5a406bcde24e663" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/SegataLab/lefse/archive/refs/tags/1.1.1.tar.gz
  sha256: 26f2f9d3e5ee44e588fab4d58bffcb811d6bdab39b6c7d0ae5a406bcde24e663

build:
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - python >=3.7
    - setuptools
    - r-base
  run:
    - python >=3.7
    - r-base
    - numpy
    - matplotlib
    - rpy2
    - r-survival
    - r-mvtnorm
    - r-modeltools
    - r-coin
    - r-MASS

test:
  commands:
    - run_lefse.py --help

about:
  home: http://huttenhower.sph.harvard.edu/lefse
  license: MIT
  license_family: MIT
  summary: 'LEfSe'
  description: 'LDA Effect Size (LEfSe) (Segata et. al 2010) is An algorithm for High-Dimensional biomarker discovery and explanation that identifies genomic features (genes, pathways, or taxa) characterizing the differences between two or more biological conditions (or classes, see figure below).'
  doc_url: http://huttenhower.sph.harvard.edu/lefse

extra:
  recipe-maintainers: 'https://forum.biobakery.org/c/downstream-analysis-and-statistics/lefse/9'
