{% set name = "mlpy" %}
{% set version = "3.5.0" %}
{% set sha256 = "344fa75fbf9f76af72f6a346d5309613defc4d244bac13c218e509a51d68bf6a" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}' 

source:
  url: https://sourceforge.net/projects/mlpy/files/mlpy%20{{ version }}/mlpy-{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install
  
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - scipy
    - gsl
  run:
    - python
    - numpy
    - scipy
    - gsl

test:
  imports:
    - mlpy

about:
  home: http://mlpy.sourceforge.net/index.html
  license: GPL3
  summary: mlpy is a Python module for Machine Learning built on top of NumPy/SciPy and the GNU Scientific Libraries.
  doc_url: http://mlpy.sourceforge.net/docs

