{% set name = "humann2" %}
{% set version = "2.8.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "1b2e646eea8de21c8ccc3bbb128e8aa57bf7e8f9901c3098cb6a0eeb10a82489" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - humann2 = humann2.humann2:main
    - humann2_databases = humann2.tools.humann2_databases:main
    - humann2_config = humann2.tools.humann2_config:main
    - humann2_join_tables = humann2.tools.join_tables:main
    - humann2_split_table = humann2.tools.split_table:main
    - humann2_rename_table = humann2.tools.rename_table:main
    - humann2_renorm_table = humann2.tools.renorm_table:main
    - humann2_regroup_table = humann2.tools.regroup_table:main
    - humann2_infer_taxonomy = humann2.tools.infer_taxonomy:main
    - humann2_humann1_kegg = humann2.tools.humann2_humann1_kegg:main
    - humann2_rna_dna_norm = humann2.tools.rna_dna_norm:main
    - humann2_strain_profiler = humann2.tools.strain_profiler:main
    - humann2_reduce_table = humann2.tools.reduce_table:main
    - humann2_unpack_pathways = humann2.tools.merge_abundance:main
    - humann2_test = humann2.tests.humann2_test:main
    - humann2_build_custom_database = humann2.tools.build_custom_database:main
    - humann2_genefamilies_genus_level = humann2.tools.genefamilies_genus_level:main
    - humann2_split_stratified_table = humann2.tools.split_stratified_table:main
    - humann2_associate = humann2.tools.humann2_associate:main
    - humann2_barplot = humann2.tools.humann2_barplot:main
    - humann2_benchmark = humann2.tools.humann2_benchmark:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - metaphlan2 >2.6.0,<2.9
    - bowtie2 >2.1
    - diamond >=0.8.22,<0.9.0
    - glpk

test:
  imports:
    - humann2
    - humann2.quantify
    - humann2.search
    - humann2.tests
    - humann2.tools
  commands:
    - humann2 --help
    - humann2_databases --help
    - humann2_config --help
    - humann2_test

about:
  home: http://huttenhower.sph.harvard.edu/humann2
  license: MIT
  license_family: MIT
  summary: 'HUMAnN2: The HMP Unified Metabolic Analysis Network 2'
  description: 'HUMAnN2 is a pipeline for efficiently and accurately determining the coverage and abundance of microbial pathways in a community from metagenomic data. Sequencing a metagenome typically produces millions of short DNA/RNA reads. This process, referred to as functional profiling, aims to describe the metabolic potential of a microbial community and its members. More generally, functional profiling answers the question: What are the microbes in my community-of-interest doing (or capable of doing)?'
  doc_url: http://huttenhower.sph.harvard.edu/humann2

extra:
  recipe-maintainers: 'humann-users@googlegroups.com'
