{% set name = "metawibele" %}
{% set version = "0.4.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d54c1b97568d688ba785713078913d0bd4ff0588363369c79ca2601fc733179a

build:
  noarch: python
  number: 0
  entry_points:
    - metawibele = metawibele.metawibele:main
    - metawibele_characterize = metawibele.workflows.characterize:main
    - metawibele_prioritize = metawibele.workflows.prioritize:main
    - metawibele_preprocess = metawibele.workflows.preprocess:main
    - metawibele_abundance_annotator = metawibele.characterize.abundance_annotator:main
    - metawibele_antiSMASH_annotator = metawibele.characterize.antiSMASH_annotator:main
    - metawibele_ddi_DOMINE_ExpAtlas = metawibele.characterize.ddi_DOMINE_ExpAtlas:main
    - metawibele_ddi_DOMINE_SIFTS = metawibele.characterize.ddi_DOMINE_SIFTS:main
    - metawibele_ddi_DOMINE_ann = metawibele.characterize.ddi_DOMINE_ann:main
    - metawibele_ddi_DOMINE_protein = metawibele.characterize.ddi_DOMINE_protein:main
    - metawibele_ddi_DOMINE_protein_family = metawibele.characterize.ddi_DOMINE_protein_family:main
    - metawibele_denovo_TM_SP = metawibele.characterize.denovo_TM_SP:main
    - metawibele_finalize_annotation = metawibele.characterize.finalize_annotation:main
    - metawibele_interproscan_annotator = metawibele.characterize.interproscan_annotator:main
    - metawibele_interproscan_pfam_protein_family = metawibele.characterize.interproscan_pfam_protein_family:main
    - metawibele_interproscan_phobius_protein_family = metawibele.characterize.interproscan_phobius_protein_family:main
    - metawibele_interproscan_protein = metawibele.characterize.interproscan_protein:main
    - metawibele_interproscan_protein_family = metawibele.characterize.interproscan_protein_family:main
    - metawibele_interproscan_signalp_protein_family = metawibele.characterize.interproscan_signalp_protein_family:main
    - metawibele_interproscan_tmhmm_protein_family = metawibele.characterize.interproscan_tmhmm_protein_family:main
    - metawibele_maaslin2 = metawibele.characterize.maaslin2:main
    - metawibele_maaslin2_annotator = metawibele.characterize.maaslin2_annotator:main
    - metawibele_maaslin2_collection = metawibele.characterize.maaslin2_collection:main
    - metawibele_maaslin2_summary = metawibele.characterize.maaslin2_summary:main
    - metawibele_metadata_format = metawibele.characterize.metadata_format:main
    - metawibele_msp_protein_family = metawibele.characterize.msp_protein_family:main
    - metawibele_mspminer_msp = metawibele.characterize.mspminer_msp:main
    - metawibele_mspminer_msp_taxonomy_annotation = metawibele.characterize.mspminer_msp_taxonomy_annotation:main
    - metawibele_mspminer_msp_uniref_annotation = metawibele.characterize.mspminer_msp_uniref_annotation:main
    - metawibele_mspminer_protein = metawibele.characterize.mspminer_protein:main
    - metawibele_mspminer_protein_family = metawibele.characterize.mspminer_protein_family:main
    - metawibele_mspminer_protein_family_taxonomy = metawibele.characterize.mspminer_protein_family_taxonomy:main
    - metawibele_pfam2go = metawibele.characterize.pfam2go:main
    - metawibele_psortb_annotator = metawibele.characterize.psortb_annotator:main
    - metawibele_psortb_protein = metawibele.characterize.psortb_protein:main
    - metawibele_psortb_protein_family = metawibele.characterize.psortb_protein_family:main
    - metawibele_sum_to_protein_family_abundance = metawibele.characterize.sum_to_protein_family_abundance:main
    - metawibele_sum_to_protein_family_stratified_abundance = metawibele.characterize.sum_to_protein_family_stratified_abundance:main
    - metawibele_summary_all_annotation = metawibele.characterize.summary_all_annotation:main
    - metawibele_summary_function_annotation = metawibele.characterize.summary_function_annotation:main
    - metawibele_summary_protein_family_uniref_annotation = metawibele.characterize.summary_protein_family_uniref_annotation:main
    - metawibele_summary_protein_uniref_annotation = metawibele.characterize.summary_protein_uniref_annotation:main
    - metawibele_uniref_annotator = metawibele.characterize.uniref_annotator:main
    - metawibele_uniref_annotator_stat = metawibele.characterize.uniref_annotator_stat:main
    - metawibele_uniref_protein = metawibele.characterize.uniref_protein:main
    - metawibele_uniref_protein_family = metawibele.characterize.uniref_protein_family:main
    - metawibele_cluster_prioritization = metawibele.prioritize.cluster_prioritization:main
    - metawibele_filter_prioritization = metawibele.prioritize.filter_prioritization:main
    - metawibele_finalize_prioritization = metawibele.prioritize.finalize_prioritization:main
    - metawibele_quantify_prioritization = metawibele.prioritize.quantify_prioritization:main
    - metawibele_combine_gene_sequences = metawibele.tools.combine_gene_sequences:main
    - metawibele_extract_cluster = metawibele.tools.extract_cluster_CD_hit:main
    - metawibele_extract_complete_ORF_seq = metawibele.tools.extract_complete_ORF_seq:main
    - metawibele_extract_non_redundance_seq = metawibele.tools.extract_non_redundance_seq:main
    - metawibele_extract_protein_coding_genes = metawibele.tools.extract_protein_coding_genes:main
    - metawibele_format_contig_sequences = metawibele.tools.format_contig_sequences:main
    - metawibele_format_protein_sequences = metawibele.tools.format_protein_sequences:main
    - metawibele_gene_abundance = metawibele.tools.gene_abundance:main
    - metawibele_gene_abundance_indexRef = metawibele.tools.gene_abundance_indexRef:main
    - metawibele_gene_catalog_abundance = metawibele.tools.gene_catalog_abundance:main
    - metawibele_abundance_RPK = metawibele.common.abundance_RPK:main
    - metawibele_abundance_RPK_gene = metawibele.common.abundance_RPK_gene:main
    - metawibele_abundance_filtering = metawibele.common.abundance_filtering:main
    - metawibele_abundance_normalization = metawibele.common.abundance_normalization:main
    - metawibele_abundance_smoothing = metawibele.common.abundance_smoothing:main
    - metawibele_combine_abundance_annotation = metawibele.common.combine_abundance_annotation:main
    - metawibele_extract_abundance_feature_subset = metawibele.common.extract_abundance_feature_subset:main
    - metawibele_extract_abundance_sample_subset = metawibele.common.extract_abundance_sample_subset:main
    - metawibele_filter_clusters = metawibele.common.filter_clusters:main
    - metawibele_filter_prevalence = metawibele.common.filter_prevalence:main
    - metawibele_join_family_abundance = metawibele.common.join_family_abundance:main
    - metawibele_split_family_abundance = metawibele.common.split_family_abundance:main
    - metawibele_transpose = metawibele.common.transpose:main
    - metawibele_split_fasta_file = metawibele.common.split_fasta_file:main
    - metawibele_download_config = metawibele.common.download_config_file:main
    - metawibele_prepare_uniprot_taxonomy = metawibele.common.prepare_uniprot_taxonomy:main
    - metawibele_prepare_uniprot_annotation = metawibele.common.prepare_uniprot_annotation:main
    - metawibele_prepare_uniref_annotation = metawibele.common.prepare_uniref_annotation:main
    - metawibele_prepare_domain_databases = metawibele.common.prepare_domain_databases:main
    - metawibele_extract_uniref_maps = metawibele.common.extract_uniref_maps:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pandas
    - scipy
    - anadama2
    # - leveldb <=0.193
    - cd-hit
    - diamond

test:
  imports:
    - metawibele
    - metawibele.characterize
    - metawibele.common
    - metawibele.prioritize
    - metawibele.tasks
    - metawibele.tools
  commands:
    - metawibele --help

about:
  home: "http://huttenhower.sph.harvard.edu/MetaWIBELE"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "MetaWIBELE: Workflow to Identify novel Bioactive Elements in microbiome"
  doc_url: "http://huttenhower.sph.harvard.edu/MetaWIBELE"

extra:
  recipe-maintainers:
    - zhangyc201211@gmail.com
