{% set name = "breadcrumbs" %}
{% set version = "0.93" %}
{% set hash_type = "sha256" %}
{% set hash_value = "06d7820a072f7c35fb031966bdfcdc120e27133925da0b9bec8c13b72fd1bf20" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '0.93.tar.gz'
  url: 'https://bitbucket.org/biobakery/breadcrumbs/get/0.93.tar.gz'

build:
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  builda:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - biom-format
    - cogent
    - mpi4py
    - pyqi
    - blist
    - r-base
    - r-vegan
    - r-optparse
    - r-ggplot2
    - r-RColorBrewer
    - bioconductor-ggtree
    - bioconductor-Biostrings
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - biom-format
    - cogent
    - mpi4py
    - pyqi
    - blist
    - r-base
    - r-vegan
    - r-optparse
    - r-ggplot2
    - r-RColorBrewer
    - bioconductor-ggtree
    - bioconductor-Biostrings

test:
  commands:
    - scriptPcoa.py --help

about:
  home: https://bitbucket.org/biobakery/breadcrumbs
  license: MIT
  license_family: MIT
  summary: 'Breadcrumbs'
  description: 'Miscellaneous Huttenhower Lab scripts'
  doc_url: https://bitbucket.org/biobakery/breadcrumbs

extra:
  recipe-maintainers: 'biobakery-users@googlegroups.com'
