{% set name = "parathaa" %}
{% set version = "0.1.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "b2dad3013578b1e800e7254c277089ac97a3a54323d8abc06ca492aa25f4b598" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/
  entry_points:
    - parathaa_run_tree_analysis = parathaa.run_tree_analysis:main
    - parathaa_run_taxa_assignment = parathaa.run_taxa_assignment:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - r-base=4.2.3
    - r-ape
    - r-castor
    - r-stringr
    - r-docopt
    - r-tidytree
    - r-dplyr
    - r-phytools
    - r-dosnow
    - r-tidyr
    - r-tdbook
    - r-ggplot2
    - r-reshape2
    - bioconductor-ggtree
    - bioconductor-treeio
    - r-openssl
    - python >=3
    - numpy
    - anadama2
  run:
    - r-base=4.2.3
    - r-ape
    - r-castor
    - r-stringr
    - r-docopt
    - r-tidytree
    - r-dplyr
    - r-phytools
    - r-dosnow
    - r-tidyr
    - r-tdbook
    - r-ggplot2
    - r-reshape2
    - bioconductor-ggtree
    - bioconductor-treeio
    - r-openssl
    - python >=3
    - numpy
    - anadama2

test:
  imports:
    - parathaa
    - parathaa.utility
  commands:
    - parathaa_run_tree_analysis --help
    - parathaa_run_taxa_assignment --help

about:
  home: http://huttenhower.sph.harvard.edu/parathaa
  license: MIT
  license_family: MIT
  summary: PARATHAA(Preserving and Assimilating Region-specific Ambiguities in Taxonomic Hierarchical Assignments for Amplicons) is a tool used for the taxonomic assignment of 16S rRNA gene sequences that takes into account the uncertainty associated with using specific variable regions/primers.
  description: PARATHAA(Preserving and Assimilating Region-specific Ambiguities in Taxonomic Hierarchical Assignments for Amplicons) is a tool used for the taxonomic assignment of 16S rRNA gene sequences that takes into account the uncertainty associated with using specific variable regions/primers.
  doc_url: http://huttenhower.sph.harvard.edu/parathaa

extra:
  recipe-maintainers: https://forum.biobakery.org/c/downstream-analysis-and-statistics/parathaa
