{% set name = "halla" %}
{% set version = "0.8.40" %}
{% set hash_type = "sha256" %}
{% set hash_value = "eabf0d5e73e41801162ca3ac73ff0bb3cf374765a9e56fae0dfb94dc06d5a334" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  entry_points:
    - halla = scripts.halla:main
    - hallagram = scripts.hallagram:main
    - halladata = scripts.synthetic_data:main
    - hallagnostic = scripts.diagnostic_plot:main
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python=3.8
    - setuptools

  run:
    - python=3.8
    - jenkspy>=0.1.5
    - matplotlib>=3.5.3
    - numpy>=1.19.0
    - pandas>=1.0.5
    - PyYAML>=5.4
    - rpy2>=3.3.5
    - scikit-learn>=0.23.1
    - scipy>=1.5.1
    - seaborn>=0.10.1
    - statsmodels>=0.11.1
    - tqdm>=4.50.2
    - r-base=4.*.*
    - r-xicor
    - r-eva

test:
  imports:
    - halla
    - scripts

  commands:
    - halla --help
    - hallagram --help
    - halladata --help
    - hallagnostic --help

about:
  home: http://huttenhower.sph.harvard.edu/halla
  license: MIT
  license_family: MIT
  summary: 'HAllA: Hierarchically All-against-All Association Testing'
  description: HAllA is a programmatic tool for performing multiple association testing between two or more heterogeneous datasets, each containing a mixture of discrete, binary, or continuous data.
  doc_url: http://huttenhower.sph.harvard.edu/halla

extra:
  recipe-maintainers: 'https://forum.biobakery.org/c/downstream-analysis-and-statistics/halla/'
