{% set name = "biobakery_workflows" %}
{% set version = "0.15.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4fa73ef5641b8b9531d4b8da09ed76a2d4d36c5cbe2a49ae257679cafd15fd5c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - biobakery_workflows = biobakery_workflows.biobakery_workflows:main
    - biobakery_workflows_databases = biobakery_workflows.biobakery_workflows_databases:main

requirements:
  build:
    - python
    - setuptools
    - anadama2
  run:
    - python
    - anadama2
    - kneaddata
    - metaphlan2
    - humann2

test:
  imports:
    - biobakery_workflows
    - biobakery_workflows.data
    - biobakery_workflows.document_templates
    - biobakery_workflows.tasks
    - tests
  commands:
    - biobakery_workflows --help
    - biobakery_workflows_databases --help

about:
  home: http://huttenhower.sph.harvard.edu/biobakery_workflows
  license: MIT
  license_family: MIT
  summary: 'bioBakery workflows: A collection of meta-omic analysis workflows'
  description: 'bioBakery workflows is a collection of workflows and tasks for executing common microbial community analyses using standardized, validated tools and parameters. Quality control and statistical summary reports are automatically generated for most data types, which include 16S amplicons, metagenomes, and metatranscriptomes. Workflows are run directly from the command line and tasks can be imported to create your own custom workflows. The workflows and tasks are built with AnADAMA2 which allows for parallel task execution locally and in a grid compute environment.'
  doc_url: http://huttenhower.sph.harvard.edu/biobakery_workflows

extra:
  recipe-maintainers: 'biobakery-users@googlegroups.com'
