{% set name = "humann" %}
{% set version = "3.0.0.alpha.3" %}
{% set pypi_filename = "humann-3.0.0a3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ pypi_filename }}.tar.gz
  sha256: d9e537513350d6fcd0bb55559623e1651f90f93733433db90da654ef5ba00aa1

build:
  number: 0
  entry_points:
    - humann = humann.humann:main
    - humann3 = humann.humann:main
    - humann_databases = humann.tools.humann_databases:main
    - humann3_databases = humann.tools.humann_databases:main
    - humann_config = humann.tools.humann_config:main
    - humann_join_tables = humann.tools.join_tables:main
    - humann_split_table = humann.tools.split_table:main
    - humann_rename_table = humann.tools.rename_table:main
    - humann_renorm_table = humann.tools.renorm_table:main
    - humann_regroup_table = humann.tools.regroup_table:main
    - humann_infer_taxonomy = humann.tools.infer_taxonomy:main
    - humann_humann1_kegg = humann.tools.humann_humann1_kegg:main
    - humann_rna_dna_norm = humann.tools.rna_dna_norm:main
    - humann_strain_profiler = humann.tools.strain_profiler:main
    - humann_reduce_table = humann.tools.reduce_table:main
    - humann_unpack_pathways = humann.tools.merge_abundance:main
    - humann_test = humann.tests.humann_test:main
    - humann_build_custom_database = humann.tools.build_custom_database:main
    - humann_genefamilies_genus_level = humann.tools.genefamilies_genus_level:main
    - humann_split_stratified_table = humann.tools.split_stratified_table:main
    - humann_associate = humann.tools.humann_associate:main
    - humann_barplot = humann.tools.humann_barplot:main
    - humann_benchmark = humann.tools.humann_benchmark:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - metaphlan >=3.0.0.alpha
    - bowtie2 >2.1
    - diamond >=0.9.24
    - glpk

test:
  imports:
    - humann
    - humann.quantify
    - humann.search
    - humann.tests
    - humann.tools
  commands:
    - humann --help
    - humann_databases --help
    - humann_config --help
    - humann_test

about:
  home: http://huttenhower.sph.harvard.edu/humann
  license: MIT
  license_family: MIT
  summary: 'HUMAnN: The HMP Unified Metabolic Analysis Network, version 3'
  description: 'HUMAnN v3 is a pipeline for efficiently and accurately determining the coverage and abundance of microbial pathways in a community from metagenomic data. Sequencing a metagenome typically produces millions of short DNA/RNA reads. This process, referred to as functional profiling, aims to describe the metabolic potential of a microbial community and its members. More generally, functional profiling answers the question: What are the microbes in my community-of-interest doing (or capable of doing)?'
  doc_url: http://huttenhower.sph.harvard.edu/humann

extra:
  recipe-maintainers: 'humann-users@googlegroups.com'
